services:

  db:
    image: postgres:13.11
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow

  app:
    image: imixs/imixs-microservice
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/workflow"
      MODEL_DEFAULT_DATA: "/home/imixs/model/ticket-en-1.0.0.bpmn"
      MODEL_DEFAULT_DATA_OVERWRITE: "true"
      # Payara-Micor ENV
      MP_OPENAPI_SERVERS: "http://localhost:8080"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    # Uncomment the following lines to add an optional single-page-application
    #volumes:
      #- ./src/app/:/opt/jboss/wildfly/standalone/deployments/imixs-microservice.war/app/

  imixsadmin:
    image: imixs/imixs-admin
    ports:
      - "8888:8080"