FROM quay.io/wildfly/wildfly:27.0.1.Final-jdk11

LABEL description="Imixs-Microservice"
LABEL maintainer="ralph.soika@imixs.com"

# Copy EclipseLink and Postgres Driver
COPY ./docker/configuration/wildfly/modules/ /opt/jboss/wildfly/modules/

# Setup configuration
COPY ./docker/configuration/wildfly/*.properties /opt/jboss/wildfly/standalone/configuration/
COPY ./docker/configuration/wildfly/standalone.xml /opt/jboss/wildfly/standalone/configuration/

# Deploy artefact
#ADD ./target/*.war /opt/jboss/wildfly/standalone/deployments/
ADD ./target/imixs-microservice/ /opt/jboss/wildfly/standalone/deployments/imixs-microservice.war/
COPY ./docker/configuration/wildfly/imixs-microservice.war.dodeploy /opt/jboss/wildfly/standalone/deployments/imixs-microservice.war.dodeploy
WORKDIR /opt/jboss/wildfly
# Run in Debug Mode
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug", "*:8787"]
